"""
Prompts package — re-exports all prompt templates for convenient importing.

Usage:
    from src.prompts import CATEGORIZE_EMAIL_PROMPT, WRITER_PROMPTS, LOG_ANALYSIS_PROMPT
"""

from .categorize import CATEGORIZE_EMAIL_PROMPT
from .rag import GENERATE_RAG_QUERIES_PROMPT, GENERATE_RAG_ANSWER_PROMPT
from .writer import (
    WRITER_BASE_PROMPT,
    WRITER_PROMPT_CIRCUIT_DOWN,
    WRITER_PROMPT_LINK_FLAPPING,
    WRITER_PROMPT_PACKET_LOSS,
    WRITER_PROMPT_MAINTENANCE,
    WRITER_PROMPT_FORTITOKEN,
    WRITER_PROMPT_GENERAL,
    WRITER_PROMPT_LOG_ANALYSIS,
    WRITER_PROMPTS,
)
from .log_analysis import LOG_ANALYSIS_PROMPT

__all__ = [
    "CATEGORIZE_EMAIL_PROMPT",
    "GENERATE_RAG_QUERIES_PROMPT",
    "GENERATE_RAG_ANSWER_PROMPT",
    "WRITER_BASE_PROMPT",
    "WRITER_PROMPT_CIRCUIT_DOWN",
    "WRITER_PROMPT_LINK_FLAPPING",
    "WRITER_PROMPT_PACKET_LOSS",
    "WRITER_PROMPT_MAINTENANCE",
    "WRITER_PROMPT_FORTITOKEN",
    "WRITER_PROMPT_GENERAL",
    "WRITER_PROMPT_LOG_ANALYSIS",
    "WRITER_PROMPTS",
    "LOG_ANALYSIS_PROMPT",
]
